tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "python"
brew "mas"

cask "1password"
cask "battle-net"
cask "bettertouchtool"
cask "discord"
cask "firefox"
cask "kitty"
cask "moom"

mas "Day One", id: 1055511498
mas "Ulysses", id: 1225570693
